---
micronaut:
    application:
        name: gateway-service
    server:
        port: 8080
        cors:
          enabled: true

---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:consul}:${CONSUL_PORT:8500}"
