omdb:
    key: "7941b866"
    url: "http://www.omdbapi.com"
---
micronaut:
    application:
        name: omdb-service
    server:
        port: 8081

---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:consul}:${CONSUL_PORT:8500}"
